swagger: '2.0'
info:
  title: Slack Bots Showcase
  description: |
    Vivere's Bots showcase
  version: 1.0.0
  contact:
    name: rafael.trestini@viverebrasil.com.br
  termsOfService: 'https://slackshowcase.viverebrasil.com.br/about.html'
basePath: /v1
schemes:
  - https
paths:
  /bot/population:
    get:
      tags:
        - Bots
      summary: 'Devolve a populacao em um dado ano, por idade'
      operationId: getPopulation
      produces:
        - application/json
      parameters:
        - in: query
          name: age
          description: Idade
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Population'
        '404':
          description: Dados nao encontrados
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Bot:
    type: object
    properties:
      id:
        type: string
      version:
        type: string
      description:
        type: string
  Population:
    type: object
    properties:
      females:
        type: integer
        format: int32
      males:
        type: integer
        format: int32
      age:
        type: integer
        format: int32
      year:
        type: integer
        format: int32
      total:
        type: integer
        format: int32
      country:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
